---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eproxy-node
  namespace: eproxy
  labels:
    app: eproxy
spec:
  selector:
    matchLabels:
      app: eproxy-node
  template:
    metadata:
      labels:
        app: eproxy-node
    spec:
      hostNetwork: true
      serviceAccount: eproxy-sa
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      hostIPC: true
      containers:
        - name: eproxy
          image: registry.cn-hangzhou.aliyuncs.com/secrity/eproxy:0.0.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:  ["/eproxy/eproxy","-ebpf","/ebpf/service.o"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eproxy-role
rules:
  - apiGroups: [""] # 空字符串""表明使用core API group
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eproxy-sa
  namespace: eproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eproxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eproxy-role
subjects:
  - kind: ServiceAccount
    name: eproxy-sa
    namespace: eproxy
